### ISSUE TITLE
Datetime arithmetic gives wrong results around DST transitions

### ISSUE THREAD

**Issue by kanwepr** [pganssle/zoneinfo#85] opened 2020-06-22 21:39 UTC
Daylight saving time in US/Eastern started at 2am on March 8th.

```
>>> import datetime
>>> from backports import zoneinfo
>>> a = datetime.datetime(2020, 3, 8, 2, 0, tzinfo=zoneinfo.ZoneInfo('US/Eastern'))
>>> b = a + datetime.timedelta(seconds=10000)
>>> print(b.timestamp() - a.timestamp())
6400.0  # this should be 10000
```

Another example:  it is an objective fact that only 23 hours passed between midnight 2020-03-08 and midnight 2020-03-09, but here we get 24.

```
>>> import datetime
>>> from backports import zoneinfo
>>> a = datetime.datetime(2020, 3, 8, tzinfo=zoneinfo.ZoneInfo('US/Eastern'))
>>> b = datetime.datetime(2020, 3, 9, tzinfo=zoneinfo.ZoneInfo('US/Eastern'))
>>> print((b - a).total_seconds() / 3600)
24.0  # this should be 23
```

Using zoneinfo 0.2.0 on Python 3.8.3 on Ubuntu 18.04.

**Comment by pganssle** [comment] 2020-06-22 21:47
Thank you for taking the time to make this report. It's very clear, and I appreciate the inclusion of two minimal reproducers!

That said, this is the intended behavior — and in fact there's nothing that this project can do about it (it would have to be a backwards-incompatible change to the language itself). `datetime` arithmetic in Python is "calendar arithmetic", not elapsed time arithmetic. I have written a [blog post about this](https://blog.ganssle.io/articles/2018/02/aware-datetime-arithmetic.html) that might interest you.

I also give some strategies for working around this both in that blog post and in [this migration guide](https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html#handling-datetime-arithmetic-normalizing-datetimes) for converting from `pytz` to a PEP 495-compatible time zone.

I'm going to close this issue, but I do appreciate you taking the time to open it (and I expect it will still be valuable even if just as something that other people confused by this issue can find via google in the future).

**Closed by pganssle** 2020-06-22 21:47 UTC
